// <auto-generated />
using System;
using CMLSmartHomeController.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMLSmartHomeController.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181027183110_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CMLSmartHome.Models.SensorRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CollectorId");

                    b.Property<long>("SensorId");

                    b.Property<int>("Unit");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("SensorRecords");
                });

            modelBuilder.Entity("CMLSmartHome.Models.SmartHomeController", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("MACAddress");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Controller");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Models.Collector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("MACAddress");

                    b.Property<string>("Name");

                    b.Property<long?>("SmartHomeControllerId");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeControllerId");

                    b.ToTable("Collectors");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Models.Sensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CollectorId");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<int>("Unit");

                    b.HasKey("Id");

                    b.HasIndex("CollectorId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Models.Collector", b =>
                {
                    b.HasOne("CMLSmartHome.Models.SmartHomeController")
                        .WithMany("Collectors")
                        .HasForeignKey("SmartHomeControllerId");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Models.Sensor", b =>
                {
                    b.HasOne("CMLSmartHomeCommon.Models.Collector")
                        .WithMany("Sensors")
                        .HasForeignKey("CollectorId");
                });
#pragma warning restore 612, 618
        }
    }
}
