// <auto-generated />
using System;
using CMLSmartHomeController.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMLSmartHomeController.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200120193205_Dashboard")]
    partial class Dashboard
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CMLSmartHomeCommon.Model.Collector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("DashboardId");

                    b.Property<string>("Description");

                    b.Property<string>("MACAddress");

                    b.Property<string>("Name");

                    b.Property<long?>("SmartHomeControllerId");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("SmartHomeControllerId");

                    b.ToTable("Collectors");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Model.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("OutdoorCollectorId");

                    b.HasKey("Id");

                    b.HasIndex("OutdoorCollectorId");

                    b.ToTable("Dashboard");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Model.Sensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CollectorId");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<int>("Unit");

                    b.HasKey("Id");

                    b.HasIndex("CollectorId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("CMLSmartHomeController.Model.SensorRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CollectorId");

                    b.Property<DateTime>("DateTime");

                    b.Property<long>("SensorId");

                    b.Property<int>("Unit");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("SensorRecords");
                });

            modelBuilder.Entity("CMLSmartHomeController.Model.SmartHomeController", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("MACAddress");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Controller");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Model.Collector", b =>
                {
                    b.HasOne("CMLSmartHomeCommon.Model.Dashboard")
                        .WithMany("InternalCollectors")
                        .HasForeignKey("DashboardId");

                    b.HasOne("CMLSmartHomeController.Model.SmartHomeController")
                        .WithMany("Collectors")
                        .HasForeignKey("SmartHomeControllerId");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Model.Dashboard", b =>
                {
                    b.HasOne("CMLSmartHomeCommon.Model.Collector", "OutdoorCollector")
                        .WithMany()
                        .HasForeignKey("OutdoorCollectorId");
                });

            modelBuilder.Entity("CMLSmartHomeCommon.Model.Sensor", b =>
                {
                    b.HasOne("CMLSmartHomeCommon.Model.Collector")
                        .WithMany("Sensors")
                        .HasForeignKey("CollectorId");
                });
#pragma warning restore 612, 618
        }
    }
}
